pipeline {
    agent any
    options {disableConcurrentBuilds()}
    environment {        
        GOOGLE_PROJECT_ID = "retro-376614" 
        GOOGLE_PROJECT_NAME = "retro"
        GOOGLE_APPLICATION_CREDENTIALS = credentials('retro')
        GOOGLE_CLOUD_KEYFILE_JSON = credentials('retro')
    }
    parameters { 
      choice(name: 'ENTORNOS', choices: ['dev', 'pre', 'pro'], description: 'Seleccione el entorno a utilizar')
      choice(name: 'ACCION', choices: ['', 'plan-apply', 'destroy', 'build', 'deploy'], description: 'Seleccione el entorno a utilizar')
    }
    stages{        
        stage('clean workspaces -----------') { 
            steps {
              cleanWs()
              sh 'env'
            } //steps
        }  //stage

        //${params.Acción}
        stage("git clone code"){
            steps {
                cleanWs()
                    checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [[$class: 'CleanCheckout']], 
                    submoduleCfg: [], 
                    userRemoteConfigs: [
                        [url: 'https://github.com/richardyantas/retro.git', credentialsId: '']
                        ]])
                sh 'pwd' 
                sh 'ls -l'
            } //steps
        }  //stage

        stage('Build') {
            steps {
                script{
                    if (params.ACCION == "build"){                
                        sh 'pip install -r requirements/prod.txt'                 
                    }
                }
            }
        }

        stage('Test') {
            steps {
                // Connect to the VM and clone repository and run app.py
                // sh 'pip install -r requirements/prod.txt' 
                sh 'python3 -m pytest' 
            }
        }
    
        stage('Terraform init----') {
         steps {
            sh 'terraform --version'            
            sh 'cd ci-cd && terraform init '
            } //steps
        }  //stage

        stage('Terraform plan----') {
            steps {
               sh 'cd ci-cd && terraform plan  -refresh=true -lock=false'
            } //steps
        }  //stage
        
        stage('Confirmación de accion') {
            steps {
                script {
                    def userInput = input(id: 'confirm', message: params.ACCION + '?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
                }
            }
        }
        
        stage('Terraform apply or destroy ----------------') {
            steps {
               sh 'echo "comienza"'
            script{  
                if (params.ACCION == "destroy"){
                         sh ' echo "llego" + params.ACCION'   
                         sh 'cd ci-cd && terraform destroy -auto-approve'
                } 
                if (params.ACCION == "plan-apply"){
                         sh ' echo  "llego" + params.ACCION'                 
                         sh 'cd ci-cd && terraform apply -refresh=true  -auto-approve'  
                }  // if
                //else {
                //         sh ' echo  "llego" + params.ACCION'                 
                //         sh 'terraform apply -refresh=true  -auto-approve'  
                // }  // if

            }
            } //steps
        }  //stage        

        // stage('Build') {
        //     // Connect to the VM and clone repository and run app.py
        //     if (params.ACCION != "build"){
        //         sh 'git clone https://github.com/richardyantas/tenpo.git '
        //     }
        // }

        // stage('Deploy') {
        //     // Connect to the VM and clone repository and run app.py
        //     if (params.ACCION != "deploy"){
        //         sh ' echo "deploying'

        //     }
        // }
   }  // stages
} //pipeline